export const CountriesList = [
    {
        Country_Code_2: "AF",
        Country_Code_3: "AFG",
        Country_Name: "Afghanistan",
        Country_Name_Full: "Islamic Republic of Afghanistan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 93,
        Currency_Name: "Afghani",
        Capital: "Kabul",
    },
    {
        Country_Code_2: "AL",
        Country_Code_3: "ALB",
        Country_Name: "Albania",
        Country_Name_Full: "Republic of Albania",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 355,
        Currency_Name: "Lek",
        Capital: "Tirana",
    },
    {
        Country_Code_2: "DZ",
        Country_Code_3: "DZA",
        Country_Name: "Algeria",
        Country_Name_Full: "People's Democratic Republic of Algeria",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 213,
        Currency_Name: "Algerian Dinar",
        Capital: "Algiers",
    },
    {
        Country_Code_2: "AD",
        Country_Code_3: "AND",
        Country_Name: "Andorra",
        Country_Name_Full: "Principality of Andorra",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 376,
        Currency_Name: "Euro",
        Capital: "Andorra la Vella",
    },
    {
        Country_Code_2: "AO",
        Country_Code_3: "AGO",
        Country_Name: "Angola",
        Country_Name_Full: "Republic of Angola",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 244,
        Currency_Name: "Kwanza",
        Capital: "Luanda",
    },
    {
        Country_Code_2: "AG",
        Country_Code_3: "ATG",
        Country_Name: "Antigua & Barbuda",
        Country_Name_Full: "Antigua and Barbuda",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-268",
        Currency_Name: "East Caribbean Dollar",
        Capital: "St. John's",
    },
    {
        Country_Code_2: "AR",
        Country_Code_3: "ARG",
        Country_Name: "Argentina",
        Country_Name_Full: "Argentine Republic",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 54,
        Currency_Name: "Argentine Peso",
        Capital: "Buenos Aires",
    },
    {
        Country_Code_2: "AM",
        Country_Code_3: "ARM",
        Country_Name: "Armenia",
        Country_Name_Full: "Republic of Armenia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 374,
        Currency_Name: "Armenian Dram",
        Capital: "Yerevan",
    },
    {
        Country_Code_2: "AU",
        Country_Code_3: "AUS",
        Country_Name: "Australia",
        Country_Name_Full: "Commonwealth of Australia",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 61,
        Currency_Name: "Australian Dollar",
        Capital: "Canberra",
    },
    {
        Country_Code_2: "AT",
        Country_Code_3: "AUT",
        Country_Name: "Austria",
        Country_Name_Full: "Republic of Austria",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 43,
        Currency_Name: "Euro",
        Capital: "Vienna",
    },
    {
        Country_Code_2: "AZ",
        Country_Code_3: "AZE",
        Country_Name: "Azarbaijan",
        Country_Name_Full: "Republic of Azerbaijan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 994,
        Currency_Name: "Azerbaijan Manat",
        Capital: "Baku",
    },
    {
        Country_Code_2: "BS",
        Country_Code_3: "BHS",
        Country_Name: "Bahamas",
        Country_Name_Full: "Commonwealth of the Bahamas",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-242",
        Currency_Name: "Bahamian Dollar",
        Capital: "Nassau",
    },
    {
        Country_Code_2: "BH",
        Country_Code_3: "BHR",
        Country_Name: "Bahrain",
        Country_Name_Full: "Kingdom of Bahrain",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 973,
        Currency_Name: "Bahraini Dinar",
        Capital: "Manama",
    },
    {
        Country_Code_2: "BD",
        Country_Code_3: "BGD",
        Country_Name: "Bangladesh",
        Country_Name_Full: "People's Republic of Bangladesh",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 880,
        Currency_Name: "Taka",
        Capital: "Dhaka",
    },
    {
        Country_Code_2: "BB",
        Country_Code_3: "BRB",
        Country_Name: "Barbados",
        Country_Name_Full: "Barbados",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-246",
        Currency_Name: "Barbados Dollar",
        Capital: "Bridgetown",
    },
    {
        Country_Code_2: "BY",
        Country_Code_3: "BLR",
        Country_Name: "Belarus",
        Country_Name_Full: "Republic of Belarus",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 375,
        Currency_Name: "Belarusian Ruble",
        Capital: "Minsk",
    },
    {
        Country_Code_2: "BE",
        Country_Code_3: "BEL",
        Country_Name: "Belgium",
        Country_Name_Full: "Kingdom of Belgium",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 32,
        Currency_Name: "Euro",
        Capital: "Brussels",
    },
    {
        Country_Code_2: "BZ",
        Country_Code_3: "BLZ",
        Country_Name: "Belize",
        Country_Name_Full: "Belize",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 501,
        Currency_Name: "Belize Dollar",
        Capital: "Belmopan",
    },
    {
        Country_Code_2: "BJ",
        Country_Code_3: "BEN",
        Country_Name: "Benin",
        Country_Name_Full: "Republic of Benin",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 229,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Porto-Novo",
    },
    {
        Country_Code_2: "BT",
        Country_Code_3: "BTN",
        Country_Name: "Bhutan",
        Country_Name_Full: "Kingdom of Bhutan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 975,
        Currency_Name: "Indian Rupee,Ngultrum",
        Capital: "Thimphu",
    },
    {
        Country_Code_2: "BO",
        Country_Code_3: "BOL",
        Country_Name: "Bolivia",
        Country_Name_Full: "Plurinational State of Bolivia",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 591,
        Currency_Name: "Boliviano",
        Capital: "Sucre",
    },
    {
        Country_Code_2: "BA",
        Country_Code_3: "BIH",
        Country_Name: "Bosnia & Herzegovina",
        Country_Name_Full: "Bosnia and Herzegovina",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 387,
        Currency_Name: "Convertible Mark",
        Capital: "Sarajevo",
    },
    {
        Country_Code_2: "BW",
        Country_Code_3: "BWA",
        Country_Name: "Botswana",
        Country_Name_Full: "Republic of Botswana",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 267,
        Currency_Name: "Pula",
        Capital: "Gaborone",
    },
    {
        Country_Code_2: "BR",
        Country_Code_3: "BRA",
        Country_Name: "Brazil",
        Country_Name_Full: "Federative Republic of Brazil",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 55,
        Currency_Name: "Brazilian Real",
        Capital: "Brasilia",
    },
    {
        Country_Code_2: "BN",
        Country_Code_3: "BRN",
        Country_Name: "Brunei Darussalam",
        Country_Name_Full: "Brunei Darussalam",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 673,
        Currency_Name: "Brunei Dollar",
        Capital: "Bandar Seri Begawan",
    },
    {
        Country_Code_2: "BG",
        Country_Code_3: "BGR",
        Country_Name: "Bulgaria",
        Country_Name_Full: "Republic of Bulgaria",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 359,
        Currency_Name: "Bulgarian Lev",
        Capital: "Sofia",
    },
    {
        Country_Code_2: "BF",
        Country_Code_3: "BFA",
        Country_Name: "Burkina Faso",
        Country_Name_Full: "Burkina Faso",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 226,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Ouagadougou",
    },
    {
        Country_Code_2: "BI",
        Country_Code_3: "BDI",
        Country_Name: "Burundi",
        Country_Name_Full: "Republic of Burundi",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 257,
        Currency_Name: "Burundi Franc",
        Capital: "Gitega",
    },
    {
        Country_Code_2: "CV",
        Country_Code_3: "CPV",
        Country_Name: "Cape Verde Islands",
        Country_Name_Full: "Republic of Cape Verde",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 238,
        Currency_Name: "Cabo Verde Escudo",
        Capital: "Praia",
    },
    {
        Country_Code_2: "KH",
        Country_Code_3: "KHM",
        Country_Name: "Cambodia",
        Country_Name_Full: "Kingdom of Cambodia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 855,
        Currency_Name: "Riel",
        Capital: "Phnom Penh",
    },
    {
        Country_Code_2: "CM",
        Country_Code_3: "CMR",
        Country_Name: "Cameroon",
        Country_Name_Full: "Republic of Cameroon",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 237,
        Currency_Name: "CFA Franc BEAC",
        Capital: "Yaounde",
    },
    {
        Country_Code_2: "CA",
        Country_Code_3: "CAN",
        Country_Name: "Canada",
        Country_Name_Full: "Canada",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 1,
        Currency_Name: "Canadian Dollar",
        Capital: "Ottawa",
    },
    {
        Country_Code_2: "TD",
        Country_Code_3: "TCD",
        Country_Name: "Chad",
        Country_Name_Full: "Republic of Chad",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 235,
        Currency_Name: "CFA Franc BEAC",
        Capital: "N'Djamena",
    },
    {
        Country_Code_2: "CL",
        Country_Code_3: "CHL",
        Country_Name: "Chile",
        Country_Name_Full: "Republic of Chile",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 56,
        Currency_Name: "Chilean Peso",
        Capital: "Santiago",
    },
    {
        Country_Code_2: "CN",
        Country_Code_3: "CHN",
        Country_Name: "China",
        Country_Name_Full: "People's Republic of China",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 86,
        Currency_Name: "Yuan Renminbi",
        Capital: "Beijing",
    },
    {
        Country_Code_2: "CO",
        Country_Code_3: "COL",
        Country_Name: "Colombia",
        Country_Name_Full: "Republic of Colombia",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 57,
        Currency_Name: "Colombian Peso",
        Capital: "Bogota",
    },
    {
        Country_Code_2: "KM",
        Country_Code_3: "COM",
        Country_Name: "Comoros",
        Country_Name_Full: "Union of the Comoros",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 269,
        Currency_Name: "Comorian Franc ",
        Capital: "Moroni",
    },
    {
        Country_Code_2: "CG",
        Country_Code_3: "COG",
        Country_Name: "Congo - Brazzaville",
        Country_Name_Full: "Republic of the Congo",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 242,
        Currency_Name: "CFA Franc BEAC",
        Capital: "Brazzaville",
    },
    {
        Country_Code_2: "CK",
        Country_Code_3: "COK",
        Country_Name: "Cook Island",
        Country_Name_Full: "Cook Islands",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 682,
        Currency_Name: "New Zealand Dollar",
        Capital: "Avarua",
    },
    {
        Country_Code_2: "CR",
        Country_Code_3: "CRI",
        Country_Name: "Costa Rica",
        Country_Name_Full: "Republic of Costa Rica",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 506,
        Currency_Name: "Costa Rican Colon",
        Capital: "San Jose",
    },
    {
        Country_Code_2: "HR",
        Country_Code_3: "HRV",
        Country_Name: "Croatia",
        Country_Name_Full: "Republic of Croatia",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 385,
        Currency_Name: "Euro",
        Capital: "Zagreb",
    },
    {
        Country_Code_2: "CU",
        Country_Code_3: "CUB",
        Country_Name: "Cuba",
        Country_Name_Full: "Republic of Cuba",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 53,
        Currency_Name: "Cuban Peso,Peso Convertible",
        Capital: "Havana",
    },
    {
        Country_Code_2: "CY",
        Country_Code_3: "CYP",
        Country_Name: "Cyprus",
        Country_Name_Full: "Republic of Cyprus",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 357,
        Currency_Name: "Euro",
        Capital: "Nicosia",
    },
    {
        Country_Code_2: "CD",
        Country_Code_3: "COD",
        Country_Name: "Congo - Kinshasa",
        Country_Name_Full: "Democratic Republic of the Congo",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 243,
        Currency_Name: "Congolese Franc",
        Capital: "Kinshasa",
    },
    {
        Country_Code_2: "DK",
        Country_Code_3: "DNK",
        Country_Name: "Denmark",
        Country_Name_Full: "Kingdom of Denmark",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 45,
        Currency_Name: "Danish Krone",
        Capital: "Copenhagen",
    },
    {
        Country_Code_2: "DJ",
        Country_Code_3: "DJI",
        Country_Name: "Djibouti",
        Country_Name_Full: "Republic of Djibouti",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 253,
        Currency_Name: "Djibouti Franc",
        Capital: "Djibouti",
    },
    {
        Country_Code_2: "DM",
        Country_Code_3: "DMA",
        Country_Name: "Dominica",
        Country_Name_Full: "Commonwealth of Dominica",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-767",
        Currency_Name: "East Caribbean Dollar",
        Capital: "Roseau",
    },
    {
        Country_Code_2: "DO",
        Country_Code_3: "DOM",
        Country_Name: "Dominican Republic",
        Country_Name_Full: "Dominican Republic",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-809,1-829,1-849",
        Currency_Name: "Dominican Peso",
        Capital: "Santo Domingo",
    },
    {
        Country_Code_2: "EC",
        Country_Code_3: "ECU",
        Country_Name: "Ecuador",
        Country_Name_Full: "Republic of Ecuador",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 593,
        Currency_Name: "US Dollar",
        Capital: "Quito",
    },
    {
        Country_Code_2: "EG",
        Country_Code_3: "EGY",
        Country_Name: "Egypt",
        Country_Name_Full: "Arab Republic of Egypt",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 20,
        Currency_Name: "Egyptian Pound",
        Capital: "Cairo",
    },
    {
        Country_Code_2: "SV",
        Country_Code_3: "SLV",
        Country_Name: "El Salvador",
        Country_Name_Full: "Republic of El Salvador",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 503,
        Currency_Name: "El Salvador Colon,US Dollar",
        Capital: "San Salvador",
    },
    {
        Country_Code_2: "GQ",
        Country_Code_3: "GNQ",
        Country_Name: "Equatorial Guinea",
        Country_Name_Full: "Republic of Equatorial Guinea",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 240,
        Currency_Name: "CFA Franc BEAC",
        Capital: "Malabo",
    },
    {
        Country_Code_2: "ER",
        Country_Code_3: "ERI",
        Country_Name: "Eritrea",
        Country_Name_Full: "State of Eritrea",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 291,
        Currency_Name: "Nakfa",
        Capital: "Asmara",
    },
    {
        Country_Code_2: "EE",
        Country_Code_3: "EST",
        Country_Name: "Estonia",
        Country_Name_Full: "Republic of Estonia",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 372,
        Currency_Name: "Euro",
        Capital: "Tallinn",
    },
    {
        Country_Code_2: "ET",
        Country_Code_3: "ETH",
        Country_Name: "Ethiopia",
        Country_Name_Full: "Federal Democratic Republic of Ethiopia",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 251,
        Currency_Name: "Ethiopian Birr",
        Capital: "Addis Ababa",
    },
    {
        Country_Code_2: "FJ",
        Country_Code_3: "FJI",
        Country_Name: "Fiji",
        Country_Name_Full: "Republic of Fiji",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 679,
        Currency_Name: "Fiji Dollar",
        Capital: "Suva",
    },
    {
        Country_Code_2: "FI",
        Country_Code_3: "FIN",
        Country_Name: "Finland",
        Country_Name_Full: "Republic of Finland",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 358,
        Currency_Name: "Euro",
        Capital: "Helsinki",
    },
    {
        Country_Code_2: "FR",
        Country_Code_3: "FRA",
        Country_Name: "France",
        Country_Name_Full: "French Republic",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 33,
        Currency_Name: "Euro",
        Capital: "Paris",
    },
    {
        Country_Code_2: "GA",
        Country_Code_3: "GAB",
        Country_Name: "Gabon",
        Country_Name_Full: "Gabonese Republic",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 241,
        Currency_Name: "CFA Franc BEAC",
        Capital: "Libreville",
    },
    {
        Country_Code_2: "GM",
        Country_Code_3: "GMB",
        Country_Name: "Gambia",
        Country_Name_Full: "Republic of the Gambia",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 220,
        Currency_Name: "Dalasi",
        Capital: "Banjul",
    },
    {
        Country_Code_2: "GE",
        Country_Code_3: "GEO",
        Country_Name: "Georgia",
        Country_Name_Full: "Georgia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 995,
        Currency_Name: "Lari",
        Capital: "Tbilisi",
    },
    {
        Country_Code_2: "DE",
        Country_Code_3: "DEU",
        Country_Name: "Germany",
        Country_Name_Full: "Federal Republic of Germany",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 49,
        Currency_Name: "Euro",
        Capital: "Berlin",
    },
    {
        Country_Code_2: "GH",
        Country_Code_3: "GHA",
        Country_Name: "Ghana",
        Country_Name_Full: "Republic of Ghana",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 233,
        Currency_Name: "Ghana Cedi",
        Capital: "Accra",
    },
    {
        Country_Code_2: "GR",
        Country_Code_3: "GRC",
        Country_Name: "Greece",
        Country_Name_Full: "Hellenic Republic Greece",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 30,
        Currency_Name: "Euro",
        Capital: "Athens",
    },
    {
        Country_Code_2: "GD",
        Country_Code_3: "GRD",
        Country_Name: "Grenada",
        Country_Name_Full: "Grenada",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-473",
        Currency_Name: "East Caribbean Dollar",
        Capital: "St. George's",
    },
    {
        Country_Code_2: "GT",
        Country_Code_3: "GTM",
        Country_Name: "Guatemala",
        Country_Name_Full: "Republic of Guatemala",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 502,
        Currency_Name: "Quetzal",
        Capital: "Guatemala City",
    },
    {
        Country_Code_2: "GN",
        Country_Code_3: "GIN",
        Country_Name: "Guinea",
        Country_Name_Full: "Republic of Guinea",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 224,
        Currency_Name: "Guinean Franc",
        Capital: "Conakry",
    },
    {
        Country_Code_2: "GW",
        Country_Code_3: "GNB",
        Country_Name: "Guinea Bissau",
        Country_Name_Full: "Republic of Guinea-Bissau",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 245,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Bissau",
    },
    {
        Country_Code_2: "GY",
        Country_Code_3: "GUY",
        Country_Name: "Guyana",
        Country_Name_Full: "Co-operative Republic of Guyana",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 592,
        Currency_Name: "Guyana Dollar",
        Capital: "Georgetown",
    },
    {
        Country_Code_2: "HT",
        Country_Code_3: "HTI",
        Country_Name: "Haiti",
        Country_Name_Full: "Republic of Haiti",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 509,
        Currency_Name: "Gourde,US Dollar",
        Capital: "Port-au-Prince",
    },
    {
        Country_Code_2: "HN",
        Country_Code_3: "HND",
        Country_Name: "Honduras",
        Country_Name_Full: "Republic of Honduras",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 504,
        Currency_Name: "Lempira",
        Capital: "Tegucigalpa",
    },
    {
        Country_Code_2: "HU",
        Country_Code_3: "HUN",
        Country_Name: "Hungary",
        Country_Name_Full: "Hungary",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 36,
        Currency_Name: "Forint",
        Capital: "Budapest",
    },
    {
        Country_Code_2: "IS",
        Country_Code_3: "ISL",
        Country_Name: "Iceland",
        Country_Name_Full: "Republic of Iceland",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 354,
        Currency_Name: "Iceland Krona",
        Capital: "Reykjavik",
    },
    {
        Country_Code_2: "IN",
        Country_Code_3: "IND",
        Country_Name: "India",
        Country_Name_Full: "Republic of India",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 91,
        Currency_Name: "Indian Rupee",
        Capital: "New Delhi",
    },
    {
        Country_Code_2: "ID",
        Country_Code_3: "IDN",
        Country_Name: "Indonesia",
        Country_Name_Full: "Republic of Indonesia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 62,
        Currency_Name: "Rupiah",
        Capital: "Jakarta",
    },
    {
        Country_Code_2: "IR",
        Country_Code_3: "IRN",
        Country_Name: "Iran",
        Country_Name_Full: "Islamic Republic of Iran",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 98,
        Currency_Name: "Iranian Rial",
        Capital: "Tehran",
    },
    {
        Country_Code_2: "IQ",
        Country_Code_3: "IRQ",
        Country_Name: "Iraq",
        Country_Name_Full: "Republic of Iraq",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 964,
        Currency_Name: "Iraqi Dinar",
        Capital: "Baghdad",
    },
    {
        Country_Code_2: "IE",
        Country_Code_3: "IRL",
        Country_Name: "Ireland",
        Country_Name_Full: "Ireland",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 353,
        Currency_Name: "Euro",
        Capital: "Dublin",
    },
    {
        Country_Code_2: "IL",
        Country_Code_3: "ISR",
        Country_Name: "Israel",
        Country_Name_Full: "State of Israel",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 972,
        Currency_Name: "New Israeli Sheqel",
        Capital: "Jerusalem",
    },
    {
        Country_Code_2: "IT",
        Country_Code_3: "ITA",
        Country_Name: "Italy",
        Country_Name_Full: "Italian Republic",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 39,
        Currency_Name: "Euro",
        Capital: "Rome",
    },
    {
        Country_Code_2: "JM",
        Country_Code_3: "JAM",
        Country_Name: "Jamaica",
        Country_Name_Full: "Jamaica",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-876",
        Currency_Name: "Jamaican Dollar",
        Capital: "Kingston",
    },
    {
        Country_Code_2: "JP",
        Country_Code_3: "JPN",
        Country_Name: "Japan",
        Country_Name_Full: "Japan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 81,
        Currency_Name: "Yen",
        Capital: "Tokyo",
    },
    {
        Country_Code_2: "JO",
        Country_Code_3: "JOR",
        Country_Name: "Jordan",
        Country_Name_Full: "Hashemite Kingdom of Jordan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 962,
        Currency_Name: "Jordanian Dinar",
        Capital: "Amman",
    },
    {
        Country_Code_2: "KZ",
        Country_Code_3: "KAZ",
        Country_Name: "Kazakhstan",
        Country_Name_Full: "Republic of Kazakhstan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 7,
        Currency_Name: "Tenge",
        Capital: "Nur-Sultan",
    },
    {
        Country_Code_2: "KE",
        Country_Code_3: "KEN",
        Country_Name: "Kenya",
        Country_Name_Full: "Republic of Kenya",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 254,
        Currency_Name: "Kenyan Shilling",
        Capital: "Nairobi",
    },
    {
        Country_Code_2: "KI",
        Country_Code_3: "KIR",
        Country_Name: "Kiribati",
        Country_Name_Full: "Republic of Kiribati",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 686,
        Currency_Name: "Australian Dollar",
        Capital: "Tarawa",
    },
    {
        Country_Code_2: "KW",
        Country_Code_3: "KWT",
        Country_Name: "Kuwait",
        Country_Name_Full: "State of Kuwait",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 965,
        Currency_Name: "Kuwaiti Dinar",
        Capital: "Kuwait City",
    },
    {
        Country_Code_2: "KG",
        Country_Code_3: "KGZ",
        Country_Name: "Kyrgyzstan",
        Country_Name_Full: "Kyrgyz Republic",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 996,
        Currency_Name: "Som",
        Capital: "Bishkek",
    },
    {
        Country_Code_2: "LA",
        Country_Code_3: "LAO",
        Country_Name: "Lao People'S Democratic Republic",
        Country_Name_Full: "Lao People's Democratic Republic",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 856,
        Currency_Name: "Lao Kip",
        Capital: "Vientiane",
    },
    {
        Country_Code_2: "LV",
        Country_Code_3: "LVA",
        Country_Name: "Latvia",
        Country_Name_Full: "Republic of Latvia",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 371,
        Currency_Name: "Euro",
        Capital: "Riga",
    },
    {
        Country_Code_2: "LB",
        Country_Code_3: "LBN",
        Country_Name: "Lebanon",
        Country_Name_Full: "Lebanese Republic",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 961,
        Currency_Name: "Lebanese Pound",
        Capital: "Beirut",
    },
    {
        Country_Code_2: "LS",
        Country_Code_3: "LSO",
        Country_Name: "Lesotho",
        Country_Name_Full: "Kingdom of Lesotho",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 266,
        Currency_Name: "Loti,Rand",
        Capital: "Maseru",
    },
    {
        Country_Code_2: "LR",
        Country_Code_3: "LBR",
        Country_Name: "Liberia",
        Country_Name_Full: "Republic of Liberia",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 231,
        Currency_Name: "Liberian Dollar",
        Capital: "Monrovia",
    },
    {
        Country_Code_2: "LY",
        Country_Code_3: "LBY",
        Country_Name: "Libya",
        Country_Name_Full: "Libya",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 218,
        Currency_Name: "Libyan Dinar",
        Capital: "Tripoli",
    },
    {
        Country_Code_2: "LI",
        Country_Code_3: "LIE",
        Country_Name: "Liechtenstein",
        Country_Name_Full: "Principality of Liechtenstein",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 423,
        Currency_Name: "Swiss Franc",
        Capital: "Vaduz",
    },
    {
        Country_Code_2: "LT",
        Country_Code_3: "LTU",
        Country_Name: "Lithuania",
        Country_Name_Full: "Republic of Lithuania",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 370,
        Currency_Name: "Euro",
        Capital: "Vilnius",
    },
    {
        Country_Code_2: "LU",
        Country_Code_3: "LUX",
        Country_Name: "Luxembourg",
        Country_Name_Full: "Grand Duchy of Luxembourg",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 352,
        Currency_Name: "Euro",
        Capital: "Luxembourg",
    },
    {
        Country_Code_2: "MG",
        Country_Code_3: "MDG",
        Country_Name: "Madagascar",
        Country_Name_Full: "Republic of Madagascar",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 261,
        Currency_Name: "Malagasy Ariary",
        Capital: "Antananarivo",
    },
    {
        Country_Code_2: "MW",
        Country_Code_3: "MWI",
        Country_Name: "Malawi",
        Country_Name_Full: "Republic of Malawi",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 265,
        Currency_Name: "Malawi Kwacha",
        Capital: "Lilongwe",
    },
    {
        Country_Code_2: "MY",
        Country_Code_3: "MYS",
        Country_Name: "Malaysia",
        Country_Name_Full: "Malaysia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 60,
        Currency_Name: "Malaysian Ringgit",
        Capital: "Kuala Lumpur",
    },
    {
        Country_Code_2: "MV",
        Country_Code_3: "MDV",
        Country_Name: "Maldives",
        Country_Name_Full: "Republic of Maldives",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 960,
        Currency_Name: "Rufiyaa",
        Capital: "Male",
    },
    {
        Country_Code_2: "ML",
        Country_Code_3: "MLI",
        Country_Name: "Mali",
        Country_Name_Full: "Republic of Mali",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 223,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Bamako",
    },
    {
        Country_Code_2: "MT",
        Country_Code_3: "MLT",
        Country_Name: "Malta",
        Country_Name_Full: "Republic of Malta",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 356,
        Currency_Name: "Euro",
        Capital: "Valletta",
    },
    {
        Country_Code_2: "MR",
        Country_Code_3: "MRT",
        Country_Name: "Mauritania",
        Country_Name_Full: "Islamic Republic of Mauritania",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 222,
        Currency_Name: "Ouguiya",
        Capital: "Nouakchott",
    },
    {
        Country_Code_2: "MU",
        Country_Code_3: "MUS",
        Country_Name: "Mauritius",
        Country_Name_Full: "Republic of Mauritius",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 230,
        Currency_Name: "Mauritius Rupee",
        Capital: "Port Louis",
    },
    {
        Country_Code_2: "MX",
        Country_Code_3: "MEX",
        Country_Name: "Mexico",
        Country_Name_Full: "United Mexican States",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 52,
        Currency_Name: "Mexican Peso",
        Capital: "Mexico City",
    },
    {
        Country_Code_2: "FM",
        Country_Code_3: "FSM",
        Country_Name: "Micronesia",
        Country_Name_Full: "Federated States of Micronesia",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 691,
        Currency_Name: "US Dollar",
        Capital: "Palikir",
    },
    {
        Country_Code_2: "MC",
        Country_Code_3: "MCO",
        Country_Name: "Monaco",
        Country_Name_Full: "Principality of Monaco",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 377,
        Currency_Name: "Euro",
        Capital: "Monaco",
    },
    {
        Country_Code_2: "MN",
        Country_Code_3: "MNG",
        Country_Name: "Mongolia",
        Country_Name_Full: "Mongolia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 976,
        Currency_Name: "Tugrik",
        Capital: "Ulaanbaatar",
    },
    {
        Country_Code_2: "ME",
        Country_Code_3: "MNE",
        Country_Name: "Montenegro",
        Country_Name_Full: "Montenegro",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 382,
        Currency_Name: "Euro",
        Capital: "Podgorica",
    },
    {
        Country_Code_2: "MA",
        Country_Code_3: "MAR",
        Country_Name: "Morocco",
        Country_Name_Full: "Kingdom of Morocco",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 212,
        Currency_Name: "Moroccan Dirham",
        Capital: "Rabat",
    },
    {
        Country_Code_2: "MZ",
        Country_Code_3: "MOZ",
        Country_Name: "Mozambique",
        Country_Name_Full: "Republic of Mozambique",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 258,
        Currency_Name: "Mozambique Metical",
        Capital: "Maputo",
    },
    {
        Country_Code_2: "MM",
        Country_Code_3: "MMR",
        Country_Name: "Myanmar",
        Country_Name_Full: "Republic of the Union of Myanmar",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 95,
        Currency_Name: "Kyat",
        Capital: "Nay Pyi Taw",
    },
    {
        Country_Code_2: "NA",
        Country_Code_3: "NAM",
        Country_Name: "Namibia",
        Country_Name_Full: "Republic of Namibia",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 264,
        Currency_Name: "Namibia Dollar,Rand",
        Capital: "Windhoek",
    },
    {
        Country_Code_2: "NR",
        Country_Code_3: "NRU",
        Country_Name: "Nauru",
        Country_Name_Full: "Republic of Nauru",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 674,
        Currency_Name: "Australian Dollar",
        Capital: "Yaren",
    },
    {
        Country_Code_2: "NP",
        Country_Code_3: "NPL",
        Country_Name: "Nepal",
        Country_Name_Full: "Federal Democratic Republic of Nepal",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 977,
        Currency_Name: "Nepalese Rupee",
        Capital: "Kathmandu",
    },
    {
        Country_Code_2: "NZ",
        Country_Code_3: "NZL",
        Country_Name: "New Zealand",
        Country_Name_Full: "New Zealand",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 64,
        Currency_Name: "New Zealand Dollar",
        Capital: "Wellington",
    },
    {
        Country_Code_2: "NI",
        Country_Code_3: "NIC",
        Country_Name: "Nicaragua",
        Country_Name_Full: "Republic of Nicaragua",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 505,
        Currency_Name: "Cordoba Oro",
        Capital: "Managua",
    },
    {
        Country_Code_2: "NE",
        Country_Code_3: "NER",
        Country_Name: "Niger",
        Country_Name_Full: "Republic of Niger",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 227,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Niamey",
    },
    {
        Country_Code_2: "NG",
        Country_Code_3: "NGA",
        Country_Name: "Nigeria",
        Country_Name_Full: "Federal Republic of Nigeria",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 234,
        Currency_Name: "Naira",
        Capital: "Abuja",
    },
    {
        Country_Code_2: "NU",
        Country_Code_3: "NIU",
        Country_Name: "Niue",
        Country_Name_Full: "Niue",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 683,
        Currency_Name: "New Zealand Dollar",
        Capital: "Alofi",
    },
    {
        Country_Code_2: "NO",
        Country_Code_3: "NOR",
        Country_Name: "Norway",
        Country_Name_Full: "Kingdom of Norway",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 47,
        Currency_Name: "Norwegian Krone",
        Capital: "Oslo",
    },
    {
        Country_Code_2: "OM",
        Country_Code_3: "OMN",
        Country_Name: "Oman",
        Country_Name_Full: "Sultanate of Oman",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 968,
        Currency_Name: "Rial Omani",
        Capital: "Muscat",
    },
    {
        Country_Code_2: "PK",
        Country_Code_3: "PAK",
        Country_Name: "Pakistan",
        Country_Name_Full: "Islamic Republic of Pakistan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 92,
        Currency_Name: "Pakistan Rupee",
        Capital: "Islamabad",
    },
    {
        Country_Code_2: "PW",
        Country_Code_3: "PLW",
        Country_Name: "Palau",
        Country_Name_Full: "Republic of Palau",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 680,
        Currency_Name: "US Dollar",
        Capital: "Melekeok",
    },
    {
        Country_Code_2: "PA",
        Country_Code_3: "PAN",
        Country_Name: "Panama",
        Country_Name_Full: "Republic of Panama",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 507,
        Currency_Name: "Balboa,US Dollar",
        Capital: "Panama City",
    },
    {
        Country_Code_2: "PG",
        Country_Code_3: "PNG",
        Country_Name: "Papua New Guinea",
        Country_Name_Full: "Independent State of Papua New Guinea",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 675,
        Currency_Name: "Kina",
        Capital: "Port Moresby",
    },
    {
        Country_Code_2: "PY",
        Country_Code_3: "PRY",
        Country_Name: "Paraguay",
        Country_Name_Full: "Republic of Paraguay",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 595,
        Currency_Name: "Guarani",
        Capital: "Asuncion",
    },
    {
        Country_Code_2: "PE",
        Country_Code_3: "PER",
        Country_Name: "Peru",
        Country_Name_Full: "Republic of Peru",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 51,
        Currency_Name: "Sol",
        Capital: "Lima",
    },
    {
        Country_Code_2: "PL",
        Country_Code_3: "POL",
        Country_Name: "Poland",
        Country_Name_Full: "Republic of Poland",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 48,
        Currency_Name: "Zloty",
        Capital: "Warsaw",
    },
    {
        Country_Code_2: "PT",
        Country_Code_3: "PRT",
        Country_Name: "Portugal",
        Country_Name_Full: "Portuguese Republic",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 351,
        Currency_Name: "Euro",
        Capital: "Lisbon",
    },
    {
        Country_Code_2: "QA",
        Country_Code_3: "QAT",
        Country_Name: "Qatar",
        Country_Name_Full: "State of Qatar",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 974,
        Currency_Name: "Qatari Rial",
        Capital: "Doha",
    },
    {
        Country_Code_2: "MD",
        Country_Code_3: "MDA",
        Country_Name: "Moldova",
        Country_Name_Full: "Republic of Moldova",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 373,
        Currency_Name: "Moldovan Leu",
        Capital: "Chisinau",
    },
    {
        Country_Code_2: "RO",
        Country_Code_3: "ROU",
        Country_Name: "Romania",
        Country_Name_Full: "Romania",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 40,
        Currency_Name: "Romanian Leu",
        Capital: "Bucharest",
    },
    {
        Country_Code_2: "RW",
        Country_Code_3: "RWA",
        Country_Name: "Rwanda",
        Country_Name_Full: "Republic of Rwanda",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 250,
        Currency_Name: "Rwanda Franc",
        Capital: "Kigali",
    },
    {
        Country_Code_2: "LC",
        Country_Code_3: "LCA",
        Country_Name: "Saint Lucia",
        Country_Name_Full: "Saint Lucia",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-758",
        Currency_Name: "East Caribbean Dollar",
        Capital: "Castries",
    },
    {
        Country_Code_2: "AS",
        Country_Code_3: "ASM",
        Country_Name: "American Samoa",
        Country_Name_Full: "American Samoa",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 685,
        Currency_Name: "Tala",
        Capital: "Apia",
    },
    {
        Country_Code_2: "WS",
        Country_Code_3: "WSM",
        Country_Name: "Samoa",
        Country_Name_Full: "Independent State of Samoa",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 685,
        Currency_Name: "Tala",
        Capital: "Apia",
    },
    {
        Country_Code_2: "SM",
        Country_Code_3: "SMR",
        Country_Name: "San Marino",
        Country_Name_Full: "Republic of San Marino",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 378,
        Currency_Name: "Euro",
        Capital: "San Marino",
    },
    {
        Country_Code_2: "SA",
        Country_Code_3: "SAU",
        Country_Name: "Saudi Arabia",
        Country_Name_Full: "Kingdom of Saudi Arabia",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 966,
        Currency_Name: "Saudi Riyal",
        Capital: "Riyadh",
    },
    {
        Country_Code_2: "SN",
        Country_Code_3: "SEN",
        Country_Name: "Senegal",
        Country_Name_Full: "Republic of Senegal",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 221,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Dakar",
    },
    {
        Country_Code_2: "RS",
        Country_Code_3: "SRB",
        Country_Name: "Serbia",
        Country_Name_Full: "Republic of Serbia",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: "381 p",
        Currency_Name: "Serbian Dinar",
        Capital: "Belgrade",
    },
    {
        Country_Code_2: "SC",
        Country_Code_3: "SYC",
        Country_Name: "Seychelles",
        Country_Name_Full: "Republic of Seychelles",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 248,
        Currency_Name: "Seychelles Rupee",
        Capital: "Victoria",
    },
    {
        Country_Code_2: "SL",
        Country_Code_3: "SLE",
        Country_Name: "Sierra Leone",
        Country_Name_Full: "Republic of Sierra Leone",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 232,
        Currency_Name: "Leone",
        Capital: "Freetown",
    },
    {
        Country_Code_2: "SG",
        Country_Code_3: "SGP",
        Country_Name: "Singapore",
        Country_Name_Full: "Republic of Singapore",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 65,
        Currency_Name: "Singapore Dollar",
        Capital: "Singapore",
    },
    {
        Country_Code_2: "SI",
        Country_Code_3: "SVN",
        Country_Name: "Slovenia",
        Country_Name_Full: "Republic of Slovenia",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 386,
        Currency_Name: "Euro",
        Capital: "Ljubljana",
    },
    {
        Country_Code_2: "SB",
        Country_Code_3: "SLB",
        Country_Name: "Solomon Islands",
        Country_Name_Full: "Solomon Islands",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 677,
        Currency_Name: "Solomon Islands Dollar",
        Capital: "Honiara",
    },
    {
        Country_Code_2: "SO",
        Country_Code_3: "SOM",
        Country_Name: "Somalia",
        Country_Name_Full: "Somali Republic",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 252,
        Currency_Name: "Somali Shilling",
        Capital: "Mogadishu",
    },
    {
        Country_Code_2: "ZA",
        Country_Code_3: "ZAF",
        Country_Name: "South Africa",
        Country_Name_Full: "Republic of South Africa",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 27,
        Currency_Name: "Rand",
        Capital: "Pretoria",
    },
    {
        Country_Code_2: "SS",
        Country_Code_3: "SSD",
        Country_Name: "South Sudan",
        Country_Name_Full: "Republic of South Sudan",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 211,
        Currency_Name: "South Sudanese Pound",
        Capital: "Juba",
    },
    {
        Country_Code_2: "ES",
        Country_Code_3: "ESP",
        Country_Name: "Spain",
        Country_Name_Full: "Kingdom of Spain",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 34,
        Currency_Name: "Euro",
        Capital: "Madrid",
    },
    {
        Country_Code_2: "LK",
        Country_Code_3: "LKA",
        Country_Name: "Sri Lanka",
        Country_Name_Full: "Democratic Socialist Republic of Sri Lanka",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 94,
        Currency_Name: "Sri Lanka Rupee",
        Capital: "Colombo",
    },
    {
        Country_Code_2: "SD",
        Country_Code_3: "SDN",
        Country_Name: "Sudan",
        Country_Name_Full: "Republic of Sudan",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 249,
        Currency_Name: "Sudanese Pound",
        Capital: "Khartoum",
    },
    {
        Country_Code_2: "SR",
        Country_Code_3: "SUR",
        Country_Name: "Suriname",
        Country_Name_Full: "Republic of Suriname",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 597,
        Currency_Name: "Surinam Dollar",
        Capital: "Paramaribo",
    },
    {
        Country_Code_2: "SE",
        Country_Code_3: "SWE",
        Country_Name: "Sweden",
        Country_Name_Full: "Kingdom of Sweden",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 46,
        Currency_Name: "Swedish Krona",
        Capital: "Stockholm",
    },
    {
        Country_Code_2: "CH",
        Country_Code_3: "CHE",
        Country_Name: "Switzerland",
        Country_Name_Full: "Swiss Confederation",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 41,
        Currency_Name: "Swiss Franc",
        Capital: "Bern",
    },
    {
        Country_Code_2: "TJ",
        Country_Code_3: "TJK",
        Country_Name: "Tajikistan",
        Country_Name_Full: "Republic of Tajikistan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 992,
        Currency_Name: "Somoni",
        Capital: "Dushanbe",
    },
    {
        Country_Code_2: "TH",
        Country_Code_3: "THA",
        Country_Name: "Thailand",
        Country_Name_Full: "Kingdom of Thailand",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 66,
        Currency_Name: "Baht",
        Capital: "Bangkok",
    },
    {
        Country_Code_2: "TG",
        Country_Code_3: "TGO",
        Country_Name: "Togo",
        Country_Name_Full: "Togolese Republic",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 228,
        Currency_Name: "CFA Franc BCEAO",
        Capital: "Lome",
    },
    {
        Country_Code_2: "TO",
        Country_Code_3: "TON",
        Country_Name: "Tonga",
        Country_Name_Full: "Kingdom of Tonga",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 676,
        Currency_Name: "Pa'anga",
        Capital: "Nuku'alofa",
    },
    {
        Country_Code_2: "TN",
        Country_Code_3: "TUN",
        Country_Name: "Tunisia",
        Country_Name_Full: "Tunisian Republic",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 216,
        Currency_Name: "Tunisian Dinar",
        Capital: "Tunis",
    },
    {
        Country_Code_2: "TR",
        Country_Code_3: "TUR",
        Country_Name: "Turkey",
        Country_Name_Full: "Republic of Turkey",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 90,
        Currency_Name: "Turkish Lira",
        Capital: "Ankara",
    },
    {
        Country_Code_2: "TM",
        Country_Code_3: "TKM",
        Country_Name: "Turkmenistan",
        Country_Name_Full: "Turkmenistan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 993,
        Currency_Name: "Turkmenistan New Manat",
        Capital: "Ashgabat",
    },
    {
        Country_Code_2: "TV",
        Country_Code_3: "TUV",
        Country_Name: "Tuvalu",
        Country_Name_Full: "Tuvalu",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 688,
        Currency_Name: "Australian Dollar",
        Capital: "Funafuti",
    },
    {
        Country_Code_2: "UG",
        Country_Code_3: "UGA",
        Country_Name: "Uganda",
        Country_Name_Full: "Republic of Uganda",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 256,
        Currency_Name: "Uganda Shilling",
        Capital: "Kampala",
    },
    {
        Country_Code_2: "UA",
        Country_Code_3: "UKR",
        Country_Name: "Ukraine",
        Country_Name_Full: "Ukraine",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 380,
        Currency_Name: "Hryvnia",
        Capital: "Kyiv",
    },
    {
        Country_Code_2: "GB",
        Country_Code_3: "GBR",
        Country_Name: "United Kingdom",
        Country_Name_Full: "United Kingdom of Great Britain & Northern Ireland",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 44,
        Currency_Name: "Pound Sterling",
        Capital: "London",
    },
    {
        Country_Code_2: "TZ",
        Country_Code_3: "TZA",
        Country_Name: "Tanzania",
        Country_Name_Full: "United Republic of Tanzania",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 255,
        Currency_Name: "Tanzanian Shilling",
        Capital: "Dodoma",
    },
    {
        Country_Code_2: "US",
        Country_Code_3: "USA",
        Country_Name: "United States",
        Country_Name_Full: "United States of America",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 1,
        Currency_Name: "US Dollar",
        Capital: "Washington",
    },
    {
        Country_Code_2: "UY",
        Country_Code_3: "URY",
        Country_Name: "Uruguay",
        Country_Name_Full: "Eastern Republic of Uruguay",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 598,
        Currency_Name: "Peso Uruguayo,Unidad Previsional",
        Capital: "Montevideo",
    },
    {
        Country_Code_2: "UZ",
        Country_Code_3: "UZB",
        Country_Name: "Uzbekistan",
        Country_Name_Full: "Republic of Uzbekistan",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 998,
        Currency_Name: "Uzbekistan Sum",
        Capital: "Tashkent",
    },
    {
        Country_Code_2: "VU",
        Country_Code_3: "VUT",
        Country_Name: "Vanuatu",
        Country_Name_Full: "Republic of Vanuatu",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 678,
        Currency_Name: "Vatu",
        Capital: "Port Vila",
    },
    {
        Country_Code_2: "VE",
        Country_Code_3: "VEN",
        Country_Name: "Venezuela",
        Country_Name_Full: "Bolivarian Republic of Venezuela",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
        Dial_Code: 58,
        Currency_Name: "BolÃ-var Soberano,BolÃ-var Soberano",
        Capital: "Caracas",
    },
    {
        Country_Code_2: "VN",
        Country_Code_3: "VNM",
        Country_Name: "Vietnam",
        Country_Name_Full: "Socialist Republic of Vietnam",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 84,
        Currency_Name: "Dong",
        Capital: "Hanoi",
    },
    {
        Country_Code_2: "YE",
        Country_Code_3: "YEM",
        Country_Name: "Yemen",
        Country_Name_Full: "Yemen",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 967,
        Currency_Name: "Yemeni Rial",
        Capital: "Sanaa",
    },
    {
        Country_Code_2: "ZM",
        Country_Code_3: "ZMB",
        Country_Name: "Zambia",
        Country_Name_Full: "Republic of Zambia",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 260,
        Currency_Name: "Zambian Kwacha",
        Capital: "Lusaka",
    },
    {
        Country_Code_2: "ZW",
        Country_Code_3: "ZWE",
        Country_Name: "Zimbabwe",
        Country_Name_Full: "Republic of Zimbabwe",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 263,
        Currency_Name: "Zimbabwe Gold",
        Capital: "Harare",
    },
    {
        Country_Code_2: "AW",
        Country_Code_3: "ABW",
        Country_Name: "Aruba",
        Country_Name_Full: "Aruba",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 297,
        Currency_Name: "Aruban Florin",
        Capital: "Oranjestad",
    },
    {
        Country_Code_2: "BM",
        Country_Code_3: "BMU",
        Country_Name: "Bermuda",
        Country_Name_Full: "Bermuda",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-441",
        Currency_Name: "Bermudian Dollar",
        Capital: "Hamilton",
    },
    {
        Country_Code_2: "NC",
        Country_Code_3: "NCL",
        Country_Name: "New Caledonia",
        Country_Name_Full: "New Caledonia",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 687,
        Currency_Name: "CFP Franc",
        Capital: "Noumea",
    },
    {
        Country_Code_2: "GL",
        Country_Code_3: "GRL",
        Country_Name: "Greenland",
        Country_Name_Full: "Greenland",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 299,
        Currency_Name: "Danish Krone",
        Capital: "Nuuk",
    },
    {
        Country_Code_2: "AI",
        Country_Code_3: "AIA",
        Country_Name: "Anguilla",
        Country_Name_Full: "Anguilla",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-264",
        Currency_Name: "East Caribbean Dollar",
        Capital: "The Valley",
    },
    {
        Country_Code_2: "MS",
        Country_Code_3: "MSR",
        Country_Name: "Montserrat",
        Country_Name_Full: "Montserrat",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: "1-664",
        Currency_Name: "East Caribbean Dollar",
        Capital: "Plymouth",
    },
    {
        Country_Code_2: "GP",
        Country_Code_3: "GLP",
        Country_Name: "Guadeloupe",
        Country_Name_Full: "Guadeloupe",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 590,
        Currency_Name: "Euro",
        Capital: "Basse-Terre",
    },
    {
        Country_Code_2: "MQ",
        Country_Code_3: "MTQ",
        Country_Name: "Martinique",
        Country_Name_Full: "Martinique",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 596,
        Currency_Name: "Euro",
        Capital: "Fort-de-France",
    },
    {
        Country_Code_2: "YT",
        Country_Code_3: "MYT",
        Country_Name: "Mayotte",
        Country_Name_Full: "Mayotte",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 262,
        Currency_Name: "Euro",
        Capital: "Mamoudzou",
    },
    {
        Country_Code_2: "RE",
        Country_Code_3: "REU",
        Country_Name: "Reunion",
        Country_Name_Full: "Reunion",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
        Dial_Code: 262,
        Currency_Name: "Euro",
        Capital: "Saint-Denis",
    },
    {
        Country_Code_2: "MF",
        Country_Code_3: "MAF",
        Country_Name: "Saint Martin",
        Country_Name_Full: "Saint Martin (French part)",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 590,
        Currency_Name: "Euro",
        Capital: "Marigot",
    },
    {
        Country_Code_2: "GI",
        Country_Code_3: "GIB",
        Country_Name: "Gibraltar",
        Country_Name_Full: "Gibraltar",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 350,
        Currency_Name: "Gibraltar Pound",
        Capital: "Gibraltar",
    },
    {
        Country_Code_2: "HK",
        Country_Code_3: "HKG",
        Country_Name: "Hong Kong",
        Country_Name_Full: "Hong Kong Special Administrative Region of China",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 852,
        Currency_Name: "Hong Kong Dollar",
        Capital: "Hong Kong",
    },
    {
        Country_Code_2: "CW",
        Country_Code_3: "CUW",
        Country_Name: "Curacao",
        Country_Name_Full: "Curacao",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 599,
        Currency_Name: "Netherlands Antillean Guilder",
        Capital: " Willemstad",
    },
    {
        Country_Code_2: "TW",
        Country_Code_3: "TWN",
        Country_Name: "Taiwan",
        Country_Name_Full: "Taiwan, Province of China",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
        Dial_Code: 886,
        Currency_Name: "New Taiwan Dollar",
        Capital: "Taipei",
    },
    {
        Country_Code_2: "TK",
        Country_Code_3: "TKL",
        Country_Name: "Tokelau",
        Country_Name_Full: "Tokelau",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: 690,
        Currency_Name: "New Zealand Dollar",
    },
    {
        Country_Code_2: "GG",
        Country_Code_3: "GGY",
        Country_Name: "Guernsey",
        Country_Name_Full: "Bailiwick of Guernsey",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 44,
        Currency_Name: "Pound Sterling",
        Capital: "St Peter Port",
    },
    {
        Country_Code_2: "IM",
        Country_Code_3: "IMN",
        Country_Name: "Isle of Man",
        Country_Name_Full: "Isle of Man",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 44,
        Currency_Name: "Pound Sterling",
        Capital: "Douglas",
    },
    {
        Country_Code_2: "JE",
        Country_Code_3: "JEY",
        Country_Name: "Jersey",
        Country_Name_Full: "Bailiwick of Jersey",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
        Dial_Code: 44,
        Currency_Name: "Pound Sterling",
        Capital: "Saint Helier",
    },
    {
        Country_Code_2: "GU",
        Country_Code_3: "GUM",
        Country_Name: "Guam",
        Country_Name_Full: "Guam",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
        Dial_Code: "1-671",
        Currency_Name: "US Dollar",
        Capital: "Hagatna",
    },
    {
        Country_Code_2: "PR",
        Country_Code_3: "PRI",
        Country_Name: "Puerto Rico",
        Country_Name_Full: "Commonwealth of Puerto Rico",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
        Dial_Code: 1,
        Currency_Name: "US Dollar",
        Capital: "San Juan",
    },
    {
        Country_Code_2: "AX",
        Country_Code_3: "ALA",
        Country_Name: "Aland Islands",
        Country_Name_Full: "Aland Islands",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "AQ",
        Country_Code_3: "ATA",
        Country_Name: "Antarctica",
        Country_Name_Full: "Antarctica (the territory South of 60 deg S)",
        Continent_Code_2: "AN",
        Continent_Name: "Antarctica",
    },
    {
        Country_Code_2: "BQ",
        Country_Code_3: "BES",
        Country_Name: "Bonaire, Saint Eustatius and Saba",
        Country_Name_Full: "Bonaire, Sint Eustatius and Saba",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "BV",
        Country_Code_3: "BVT",
        Country_Name: "Bouvet Island (Bouvetoya)",
        Country_Name_Full: "Bouvet Island (Bouvetoya)",
        Continent_Code_2: "AN",
        Continent_Name: "Antarctica",
    },
    {
        Country_Code_2: "IO",
        Country_Code_3: "IOT",
        Country_Name: "British Indian Ocean Territory (Chagos Archipelago)",
        Country_Name_Full: "British Indian Ocean Territory (Chagos Archipelago)",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "VG",
        Country_Code_3: "VGB",
        Country_Name: "British Virgin Islands",
        Country_Name_Full: "British Virgin Islands",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "KY",
        Country_Code_3: "CYM",
        Country_Name: "Cayman Islands",
        Country_Name_Full: "Cayman Islands",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "CF",
        Country_Code_3: "CAF",
        Country_Name: "Central African Republic",
        Country_Name_Full: "Central African Republic",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
    },
    {
        Country_Code_2: "CX",
        Country_Code_3: "CXR",
        Country_Name: "Christmas Island",
        Country_Name_Full: "Christmas Island",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "CC",
        Country_Code_3: "CCK",
        Country_Name: "Cocos (Keeling) Islands",
        Country_Name_Full: "Cocos (Keeling) Islands",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "CI",
        Country_Code_3: "CIV",
        Country_Name: "Cote D Ivoire",
        Country_Name_Full: "Republic of Cote d'Ivoire",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
    },
    {
        Country_Code_2: "CZ",
        Country_Code_3: "CZE",
        Country_Name: "Czech Republic",
        Country_Name_Full: "Czech Republic",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "FK",
        Country_Code_3: "FLK",
        Country_Name: "Falkland Islands (Malvinas)",
        Country_Name_Full: "Falkland Islands (Malvinas)",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
    },
    {
        Country_Code_2: "FO",
        Country_Code_3: "FRO",
        Country_Name: "Faroe Islands",
        Country_Name_Full: "Faroe Islands",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "GF",
        Country_Code_3: "GUF",
        Country_Name: "French Guiana",
        Country_Name_Full: "French Guiana",
        Continent_Code_2: "SA",
        Continent_Name: "South America",
    },
    {
        Country_Code_2: "PF",
        Country_Code_3: "PYF",
        Country_Name: "French Polynesia",
        Country_Name_Full: "French Polynesia",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "TF",
        Country_Code_3: "ATF",
        Country_Name: "French Southern Territories",
        Country_Name_Full: "French Southern Territories",
        Continent_Code_2: "AN",
        Continent_Name: "Antarctica",
    },
    {
        Country_Code_2: "HM",
        Country_Code_3: "HMD",
        Country_Name: "Heard & Macdonald Island",
        Country_Name_Full: "Heard Island and McDonald Islands",
        Continent_Code_2: "AN",
        Continent_Name: "Antarctica",
    },
    {
        Country_Code_2: "VA",
        Country_Code_3: "VAT",
        Country_Name: "Holy See (Vatican City State)",
        Country_Name_Full: "Holy See (Vatican City State)",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "MO",
        Country_Code_3: "MAC",
        Country_Name: "Macao",
        Country_Name_Full: "Macao Special Administrative Region of China",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "MK",
        Country_Code_3: "MKD",
        Country_Name: "Macedonia",
        Country_Name_Full: "Republic of Macedonia",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "MH",
        Country_Code_3: "MHL",
        Country_Name: "Marshall Islands",
        Country_Name_Full: "Republic of the Marshall Islands",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "NL",
        Country_Code_3: "NLD",
        Country_Name: "Netherlands",
        Country_Name_Full: "Kingdom of the Netherlands",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "NF",
        Country_Code_3: "NFK",
        Country_Name: "Norfolk Island",
        Country_Name_Full: "Norfolk Island",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "KP",
        Country_Code_3: "PRK",
        Country_Name: "North Korea",
        Country_Name_Full: "Democratic People's Republic of Korea",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "MP",
        Country_Code_3: "MNP",
        Country_Name: "Northern Mariana Islands",
        Country_Name_Full: "Commonwealth of the Northern Mariana Islands",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "PS",
        Country_Code_3: "PSE",
        Country_Name: "Palestinian Territory",
        Country_Name_Full: "Occupied Palestinian Territory",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "PH",
        Country_Code_3: "PHL",
        Country_Name: "Philippines",
        Country_Name_Full: "Republic of the Philippines",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "PN",
        Country_Code_3: "PCN",
        Country_Name: "Pitcairn Islands",
        Country_Name_Full: "Pitcairn Islands",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "RU",
        Country_Code_3: "RUS",
        Country_Name: "Russia",
        Country_Name_Full: "Russian Federation",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "BL",
        Country_Code_3: "BLM",
        Country_Name: "Saint Barthelemy",
        Country_Name_Full: "Saint Barthélemy",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "KN",
        Country_Code_3: "KNA",
        Country_Name: "Saint Kitts & Nevis",
        Country_Name_Full: "Federation of Saint Kitts and Nevis",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "SX",
        Country_Code_3: "SXM",
        Country_Name: "Saint Martin (Dutch part)",
        Country_Name_Full: "Sint Maarten (Dutch part)",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "PM",
        Country_Code_3: "SPM",
        Country_Name: "Saint Pierre & Miquelon",
        Country_Name_Full: "Saint Pierre and Miquelon",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "VC",
        Country_Code_3: "VCT",
        Country_Name: "Saint Vincent & The Grenadines",
        Country_Name_Full: "Saint Vincent and the Grenadines",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "ST",
        Country_Code_3: "STP",
        Country_Name: "Sao Tome & Principe",
        Country_Name_Full: "Democratic Republic of Sao Tome and Principe",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
    },
    {
        Country_Code_2: "SK",
        Country_Code_3: "SVK",
        Country_Name: "Slovakia (Slovak Republic)",
        Country_Name_Full: "Slovakia (Slovak Republic)",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "GS",
        Country_Code_3: "SGS",
        Country_Name: "South Georgia and the South Sandwich Islands",
        Country_Name_Full: "South Georgia and the South Sandwich Islands",
        Continent_Code_2: "AN",
        Continent_Name: "Antarctica",
    },
    {
        Country_Code_2: "KR",
        Country_Code_3: "KOR",
        Country_Name: "South Korea",
        Country_Name_Full: "Republic of Korea",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "SH",
        Country_Code_3: "SHN",
        Country_Name: "St Helena & Ascension Island",
        Country_Name_Full: "Saint Helena, Ascension and Tristan da Cunha",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
    },
    {
        Country_Code_2: "SJ",
        Country_Code_3: "SJM",
        Country_Name: "Svalbard & Jan Mayen Islands",
        Country_Name_Full: "Svalbard & Jan Mayen Islands",
        Continent_Code_2: "EU",
        Continent_Name: "Europe",
    },
    {
        Country_Code_2: "SZ",
        Country_Code_3: "SWZ",
        Country_Name: "Swaziland",
        Country_Name_Full: "Kingdom of Swaziland",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
    },
    {
        Country_Code_2: "SY",
        Country_Code_3: "SYR",
        Country_Name: "Syrian Arab Republic",
        Country_Name_Full: "Syrian Arab Republic (Syria)",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "TL",
        Country_Code_3: "TLS",
        Country_Name: "Timor Leste",
        Country_Name_Full: "Democratic Republic of Timor-Leste",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "TT",
        Country_Code_3: "TTO",
        Country_Name: "Trinidad & Tobago",
        Country_Name_Full: "Republic of Trinidad and Tobago",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "TC",
        Country_Code_3: "TCA",
        Country_Name: "Turks & Caicos Islands",
        Country_Name_Full: "Turks and Caicos Islands",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "AE",
        Country_Code_3: "ARE",
        Country_Name: "United Arab Emirates",
        Country_Name_Full: "United Arab Emirates",
        Continent_Code_2: "AS",
        Continent_Name: "Asia",
    },
    {
        Country_Code_2: "UM",
        Country_Code_3: "UMI",
        Country_Name: "United States Minor Outlying Islands",
        Country_Name_Full: "United States Minor Outlying Islands",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "VI",
        Country_Code_3: "VIR",
        Country_Name: "US Virgin Islands",
        Country_Name_Full: "United States Virgin Islands",
        Continent_Code_2: "NA",
        Continent_Name: "North America",
    },
    {
        Country_Code_2: "WF",
        Country_Code_3: "WLF",
        Country_Name: "Wallis & Futuna Island",
        Country_Name_Full: "Wallis and Futuna",
        Continent_Code_2: "OC",
        Continent_Name: "Oceania",
    },
    {
        Country_Code_2: "EH",
        Country_Code_3: "ESH",
        Country_Name: "Western Sahara",
        Country_Name_Full: "Western Sahara",
        Continent_Code_2: "AF",
        Continent_Name: "Africa",
    },
];